Develop (#27)
* fix: formatted days to yyyy-mm-dd
fix: fixed data vlidation using pydantic

* removed unused import datetime

* changed from union type with None to Optional

* added datetime.datetime to formats that convert_to_dict checks for formatting

* 19 implement database connection check for healthz endpoint (#21)

* moved utility functions in util module

* adding __init__.py to make utils a module

* Implemented database health check by running a simple query

* Implemented retrying mechanism to wait for database to start running before running integration tests

* adding DB_USER and DB_PASSWORD as secrets to github action

* fixing problem with ci vars

---------

Co-authored-by: shahab <oveysi.shahab@gmail.com>

* 16 write unit tests (#25)

* test: Unittest for healthz endpoint

* test: Unittest for convert_to_dict

* test: Unittest for execute_query

* test: Unittest for rates endpoint

* test: adding docstrings to unittest for more clarity

---------

Co-authored-by: shahab <oveysi.shahab@gmail.com>

* 17 optimize query (#26)

* query: using COALESCE to null any unavailable price
using from on generate_series to make it more readable

* query: using having instead of CASE for better performance

* query: adding WHERE r.slug IS NOT NONE to end of recursion to make sure only compile correct data

* query: adding index and constraints on table

* Documenting proposal for optimization potentials

---------

Co-authored-by: shahab <oveysi.shahab@gmail.com>

---------

Co-authored-by: shahab <oveysi.shahab@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,6 +9,7 @@ on:
 jobs:
   lint_and_test:
     runs-on: ubuntu-latest
+    environment: test
 
     services:
       docker:
@@ -20,6 +21,16 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
+
+    - name: Test env
+      run: |
+        if [ -z "$DB_USER" ] || [ -z "$DB_PASSWORD" ]; then
+          echo "ERROR: DB_USER or DB_PASSWORD is not set."
+          exit 1
+        fi
+      env:
+        DB_USER: ${{ vars.DB_USER }}
+        DB_PASSWORD: ${{ vars.DB_PASSWORD }}
 
     - name: Set up Docker
       uses: docker/setup-buildx-action@v2
@@ -35,6 +46,8 @@ jobs:
         make test
       env:
         DOCKER_BUILDKIT: 1
+        DB_USER: ${{ vars.DB_USER }}
+        DB_PASSWORD: ${{ vars.DB_PASSWORD }}
 
     - name: Stop and remove containers
       run: |
