checking env before running

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,6 +22,16 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v3
 
+    - name: Test env
+      run: |
+        if [ -z "$DB_USER" ] || [ -z "$DB_PASSWORD" ]; then
+          echo "ERROR: DB_USER or DB_PASSWORD is not set."
+          exit 1
+        fi
+      env:
+        DB_USER: ${{ env.DB_USER }}
+        DB_PASSWORD: ${{ env.DB_PASSWORD }}
+
     - name: Set up Docker
       uses: docker/setup-buildx-action@v2
 
